### ISSUE TITLE
Updating to the latest version of Semantic UI

### ISSUE THREAD

**Issue by JamesChevalier** [doabit/semantic-ui-sass#101]
I was looking through the changelog, and the [2.2.9.0 release notes](https://github.com/doabit/semantic-ui-sass/blob/master/CHANGELOG.md#2290) indicate:

> Update Semantic UI to 2.2.9

However, the [semantic-ui.js](https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/javascripts/semantic-ui.js) file is at [version 2.1.7](https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/javascripts/semantic-ui.js#L2).

I poked around through the CSS files, and I noticed that the [_site.scss](https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/stylesheets/semantic-ui/globals/_site.scss) file is at [version 2.2.9](https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/stylesheets/semantic-ui/globals/_site.scss#L2).

So, it looks like you missed the update to that semantic-ui.js file. Would you like a pull request to bring that up to date?

**Comment by doabit** [comment]
@JamesChevalier Sorry for the mistake, i've updated the [semantic-ui.js](https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/javascripts/semantic-ui.js)

**Comment by JamesChevalier** [comment]
Thank you, @doabit but this has caused an error when accessing any page:

```
Sprockets::FileNotFound - couldn't find file 'api' with type 'application/javascript'
```

Based on [the history of the semantic-ui.js file](https://github.com/doabit/semantic-ui-sass/commits/master/app/assets/javascripts/semantic-ui.js), I think that it's supposed to contain lines formatted like:

```
//= require semantic-ui/api
```

instead of like:

```
//= require api
```
