### ISSUE TITLE
Newest version and Rails 5.0.2

### ISSUE THREAD

**Issue by sevos** [doabit/semantic-ui-sass#102]
If I use the newest version, I am getting following error when running Capybara:

```
Failure/Error: <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    ActionView::Template::Error:
      couldn't find file 'api' with type 'application/javascript'
```

Revision `4abe03d57f2be11d8759823a440e62e8fb1afe77` works like a charm

**Comment by doabit** [comment]
@sevos Any demo code?

**Comment by conormacken** [comment]
The fix [here](https://github.com/doabit/semantic-ui-sass/issues/101#issuecomment-284005520) on #101 seems to do the trick.

No idea how/why though.

**Comment by conormacken** [comment]
This looks like an error I'm getting & it seems to be the same one as #101.

**Comment by doabit** [comment]
I've merged it and it should work now, sorry for the big mistake.
