### ISSUE TITLE
Semantic icon helper undefined in rspec

### ISSUE THREAD

**Issue by ptylde** [doabit/semantic-ui-sass#104]
I'm testing a helper with rspec and I'm getting an undefined method error for the semantic_icon() helper.
The helper works fine in the development environment.

 
     Failure/Error: semantic_icon('attention icon')
     NoMethodError:
       undefined method `semantic_icon' for #<#<Class:0x00000002f9c688>:0x000000065de3b8>
     # ./app/helpers/customers_helper.rb:21:in `no_show_count_row'
     # ./spec/helpers/customers_helper_spec.rb:36:in `block (4 levels) in <top (required)>'

Is there a way to include the helper in rspec config?

**Comment by doabit** [comment]
@ptylde  Hi, you should test it like this

```
  render text: helper.no_show_count_row
```

**Comment by ptylde** [comment]
Still get the same error running the test like that. I tried including the helper module in the rspec config block with no luck. However, if I add `include SemanticIconHelper` to my spec file, the error goes away and the tests pass.

**Comment by ptylde** [comment]
My apologies, I figured out what the problem was. I forgot that I had set `config.action_controller.include_all_helpers = false` in my app's config. Thanks for the help!
