### ISSUE TITLE
Adjusting site variables

### ISSUE THREAD

**Issue by kuroshhashemi** [doabit/semantic-ui-sass#105]
I want to adjust some global variables such as @primaryColor and @secondaryColor.  How would I go about doing this with semantic-ui-sass?

**Comment by doabit** [comment]
@kuroshhashemi Sorry, no way now.

**Comment by kuroshhashemi** [comment]
Hi @doabit thanks for the response.  Main thing I wanted was to align is button colors to rest of my website colors.  Is there a temporary workaround even?  Sorry - I'm new to SASS so still figuring my way around

**Comment by doabit** [comment]
@kuroshhashemi Sorry, the gem has no way to do that. see https://github.com/doabit/semantic-ui-sass/issues/31

**Comment by emaildano** [comment]
@doabit Setting up these vars would be an easy search / replace with an addition to the vars files.

What is your work flow for updating this?

If you are keeping this up with the gem adding in those vars would break that flow, if not I'd be open to doing a PR for this request.

If you are keeping this updated as the gem gets updates, then we could suggest this there instead.

**Comment by doabit** [comment]
@emaildano Welcome PR.
