### ISSUE TITLE
Bug in 2.2.9

### ISSUE THREAD

**Issue by bnd170** [doabit/semantic-ui-sass#107]
> Error: Undefined variable: "$font-family".
        on line 25 of ../../../../node_modules/semantic-ui-sass/app/assets/stylesheets/semantic-ui/elements/_button.scss
>   font-family: $font-family;

Seems like the variables aren't importing in the correct order.

**Comment by doabit** [comment]
@bnd170 Sorry, i've not published this to npm.

**Comment by bnd170** [comment]
Then it is already fixed?

Thanks a lot!

**Comment by doabit** [comment]
@bnd170 Sorry,the npm package published by another man.  https://www.npmjs.com/package/semantic-ui-sass

**Comment by cmelone** [comment]
You could try to publish it under `semantic-sass`. Look at https://github.com/twbs/bootstrap-sass for a good structure.
