### ISSUE TITLE
Icons stopped working in 2.2.10.0

### ISSUE THREAD

**Issue by kamil-l** [doabit/semantic-ui-sass#109]
`ActionController::RoutingError (No route matches [GET] "/images/semantic-ui/flags.png"):`
Setting ref: '308d74a' in Gemfile solves the problem.

**Comment by doabit** [comment]
@kamil-l Sorry, please update to 2.2.10.1.

**Comment by mroach** [comment]
@doabit Correct me if I'm wrong, but that version doesn't seem to exist.

**Comment by doabit** [comment]
@mroach https://rubygems.org/gems/semantic-ui-sass, updated at a few days ago.
