### ISSUE TITLE
why pointing to Github in Gemfile?

### ISSUE THREAD

**Issue by Ana06** [doabit/semantic-ui-sass#114]
Is there any reason why you say in the [installation and usage setion of the README](https://github.com/doabit/semantic-ui-sass#installation-and-usage) that the Github version should be installed? Why not using the last stable version from Rubygems? :confused:

**Comment by doabit** [comment]
@Ana06 i've updated README.

**Comment by Ana06** [comment]
Great! I close this then! :+1:
