### ISSUE TITLE
Visibility OnBottomVisible Not Firing

### ISSUE THREAD

**Issue by ubermanl** [doabit/semantic-ui-sass#115]
https://github.com/doabit/semantic-ui-sass/blob/5a905715ed65caf74ceb8bbca1d7d839b5c4b178/app/assets/javascripts/semantic-ui/visibility.js#L931

Has been fixed in
https://github.com/Semantic-Org/Semantic-UI/pull/5363/files

**Comment by doabit** [comment]
@ubermanl You are right, but the PR haven't merged, the gem used Semantic-UI master branch.
