### ISSUE TITLE
Support Sprockets?

### ISSUE THREAD

**Issue by bananaappletw** [doabit/semantic-ui-sass#118]
Maybe support sprockets?
If it supports, it could be used on jekyll too.
That'll be great.
I have made some tweaks to let this gem work for sprockets.
If this project is going to support sprockets, I am glad to contribute my tweaks.
Thank you.

**Comment by doabit** [comment]
Sorry, i'll take a look at that and welcome a PR, thanks.

**Comment by bananaappletw** [comment]
@doabit 
You could could change the repo's description, it supports sprocket now.
