### ISSUE TITLE
Error in parsing values in web console

### ISSUE THREAD

**Issue by limciana** [doabit/semantic-ui-sass#121]
Followed the directions to install the semantic-ui-sass gem, included import statements to .scss files also, and required semantic-ui in application.js.

Running the Rails server, and opening the console shows this.

Is this something to be worried about?

![screenshot from 2017-11-19 15-55-12](https://user-images.githubusercontent.com/15266219/32988600-59907606-cd42-11e7-940c-e60c457b9041.png)

**Comment by doabit** [comment]
Which version?

**Comment by limciana** [comment]
semantic-ui-sass: 2.2.12.1
sass: 3.5.3
rails: 5.0.6

**Comment by doabit** [comment]
@limciana  I've tested and it works well on my mac, 
![edb3c3b8-8960-4745-a444-1ee37641989e](https://user-images.githubusercontent.com/330368/33105389-d20dda02-cf67-11e7-9aa9-25069707475c.png)
![20671d3c-f1bf-4703-a082-d91efaa14e74](https://user-images.githubusercontent.com/330368/33105371-ba32d7e8-cf67-11e7-8a33-f3c2677cfae3.png)


![28ad9d01-f352-476b-b036-6193c256e8ae](https://user-images.githubusercontent.com/330368/33105367-b7fd8ae0-cf67-11e7-96a0-99c2758d0501.png)

**Comment by limciana** [comment]
I did exactly those.

I re-did my Rails app, and it still had the errors.

The steps:
1.  my Gemfile
`source 'https://rubygems.org'

gem 'rails'

gem 'mysql2', '>= 0.3.13', '< 0.5'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

gem 'composite_primary_keys', '~> 9.0', '>= 9.0.8'

gem 'semantic-ui-sass'


group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 3.0'

  gem 'spring'
end`

2. ran `rails generate scaffold locs`

3. included `@import "semantic-ui` to `locs.scss,` and `//= require semantic-ui` to `application.js`

4. ran `rails s`, and opened localhost, and the error is still there

![screenshot from 2017-11-23 08-54-56](https://user-images.githubusercontent.com/15266219/33155503-15f303c2-d02c-11e7-8e5a-f516092f39e1.png)

![Uploading Screenshot from 2017-11-23 08-56-06.png…]()

**Comment by doabit** [comment]
Your browser is firefox?

**Comment by limciana** [comment]
yes, my browser is firefox

**Comment by doabit** [comment]
Could you see errors when use https://semantic-ui.com/dist/semantic.min.css to replace `application.css` ?

**Comment by limciana** [comment]
there were now less errors!

Also, update. I tried to run the code in Google Chrome also, and the warnings weren't appearing. However, there were css elements that were crossed out.

The left panel is from Google Chrome, and the right panel is from Firefox.

![screenshot from 2017-11-25 17-38-45](https://user-images.githubusercontent.com/15266219/33229327-b952d998-d207-11e7-90d2-de51d9ff1d34.png)

**Comment by doabit** [comment]
In chrome, some css elements that were crossed out because of chrome does not support the css attributes that start with `-webkit`.

**Comment by doabit** [comment]
I also tested in firefox 57 and have't appear there errors.  when you use `https://semantic-ui.com/dist/semantic.min.css`, appear any error?

**Comment by limciana** [comment]
I ran rails s again, and the errors are back.

Yes, the errors were still there.

**Comment by doabit** [comment]
@limciana If use `https://semantic-ui.com/dist/semantic.min.css` still have errors, i think you can open a new issue for https://github.com/Semantic-Org/Semantic-UI.
