### ISSUE TITLE
$(...).sidebar is not a function

### ISSUE THREAD

**Issue by Guillaumejfrt** [doabit/semantic-ui-sass#122]
Hi,

I've been using gem `semantic-ui-sass` for several months and my sidebar has always toggled perfectly. However, it doesn't work anymore. JS in the console says `$(...).sidebar is not a function`. I don't understand is going wrong. Here is my code in my js file:
```
$("#ui-sidebar").sidebar("attach events", ".sidebar-item");
```

Could you help me?

Thanks

**Comment by doabit** [comment]
![image](https://user-images.githubusercontent.com/330368/33118133-cf39c032-cfa5-11e7-9e35-67febaf706f4.png)
I tested and it seems work, could you paste your sample code?

**Comment by Guillaumejfrt** [comment]
Yes the the selector `$("#ui-sidebar")` do work. It's the semantic function `.sidebar()` which is not working.

I am not sure to understand which part of my code you want to see. Do you want me to send the html part?

**Comment by doabit** [comment]
This is my javascript code:

```javascript
//= require rails-ujs
//= require turbolinks
//= require jquery
//= require semantic-ui
```
and this is html

```html
<div id="ui-sidebar">
  <div class="sidebar-item">demo</div>
</div>
```

**Comment by Guillaumejfrt** [comment]
yes I have the same:

//= require jquery
//= require jquery_ujs
//= require semantic-ui
//= require_tree ./channels
//= require_tree .


and

<div class="ui vertical inverted sidebar menu left" id="ui-sidebar">
    <% @chatrooms.each do |chatroom| %>
      
      <%= link_to chatroom, class:"sidebar-item", remote: true do %>
        <div class="item">
          <%= image_tag chatroom.fb_user.profile_pic, class:"ui avatar
image", alt:"patient picture" %>
          <div>
            <p><%= chatroom.fb_user.first_name %> <%=
chatroom.fb_user.last_name %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

**Comment by doabit** [comment]
Please paste your layout code, and where the `$("#ui-sidebar").sidebar("attach events", ".sidebar-item");` code you put.
