### ISSUE TITLE
File to import not found or unreadable: semantic-ui.)

### ISSUE THREAD

**Issue by wernerlaude** [doabit/semantic-ui-sass#126]
Thanks for supplying your gem.. 
But I get: error application.scss (Line 8: File to import not found or unreadable: semantic-ui.)
Rails 5.2.0.rc1
Ruby 2.5.0p0
also
Rails 5.1.5
Ruby 2.3.4p301

**Comment by doabit** [comment]
@wernerlaude Which version? i've tested with rails 5.2.0.rc1.
application.css

```
/*
 *= require demo
 *= require_self
 */
```

demo.scss

```
@import 'semantic-ui';
```
