### ISSUE TITLE
Release of semantic-ui-sass

### ISSUE THREAD

**Issue by maalej** [doabit/semantic-ui-sass#129]
Is it possible to create a new release for each semantic-ui version please?

**Comment by doabit** [comment]
Sorry, I'll create a new release from now.

**Comment by jbwl** [comment]
Sorry to be a bit pushy, but the latest semantic-ui version contains some important fixes for me, could you update the gem, please?

**Comment by doabit** [comment]
@jbwl Updated.

**Comment by jbwl** [comment]
Thank you very much, that was fast!
