### ISSUE TITLE
some icons are missing

### ISSUE THREAD

**Issue by adas172002** [doabit/semantic-ui-sass#130]
Hi there,

It seems that upgrade to FontAwesome 5.0 broke some icons. Eg. [i.icon.excel.outline](https://fontawesome.com/icons/file-excel?style=regular), but I guess that all icons moved to `far` – regular style – are now missing. 

At first I realised that icons from regular style are only available in Pro version of FA, but it seems that all icons that migrated from 4.7 are still here, however issue is that semantic-ui-sass does not use new font files. Currently there is just semantic-ui-sass/app/assets/fonts/semantic-ui/icons file, while free version 5.0 of font awesome is now 3 font files: regular, brands and solid [Font-Awesome github](https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/webfonts).

[Default style](https://github.com/Semantic-Org/Semantic-UI/tree/master/src/themes/default/assets/fonts) of SUI is also using them.

**Comment by msmiller** [comment]
I think I saw an error fly about about outline.otf or something like that being missing when trying to use an outlined icon.

**Comment by doabit** [comment]
Fixed #128

**Comment by adas172002** [comment]
Thanks, this was pretty quick fix.
