### ISSUE TITLE
Reveal element

### ISSUE THREAD

**Issue by everaldo** [doabit/semantic-ui-sass#131]
Hi!

Does semantic-ui-sass include support to reveal element?

I couldn't find a file with that name and wasn't able to use this feature.

https://semantic-ui.com/elements/reveal.html

Thanks!

**Comment by doabit** [comment]
Yes, https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/stylesheets/semantic-ui/elements/_reveal.scss

it can work

```
<div class="ui instant move reveal">
  <div class="visible content">
    <img src="https://semantic-ui.com/images/wireframe/square-image.png" class="ui small image">
  </div>
  <div class="hidden content">
    <img src="https://semantic-ui.com/images/avatar/large/chris.jpg" class="ui small image">
  </div>
</div>
```
