### ISSUE TITLE
Support Fomantic-UI, a community fork

### ISSUE THREAD

**Issue by shanecav84** [doabit/semantic-ui-sass#135]
From the [Fomantic-UI README](https://github.com/fomantic/Fomantic-UI/blob/effcf62ef3aa214218072356a1b05ebd810351d7/README.md):

> NOTE: Fomantic was created to continue active development of Semantic-UI and has the intent to be merged back into the master repository once active development can restart. For more info please read the following issues https://github.com/Semantic-Org/Semantic-UI/issues/6109 https://github.com/Semantic-Org/Semantic-UI/issues/6413

I would like to help make this happen. If you would prefer not to support adding fomantic, I will probable create a separate gem.

**Comment by doabit** [comment]
Sorry, I think you can create a new gem, it should be perfect if  Fomantic-UI can support sass native.

**Comment by shanecav84** [comment]
No problem. Fomantic-UI intends to be merged back into master, so I don't think it will support sass. Thanks!

**Comment by shanecav84** [comment]
Fork for Fomantic UI is here: https://github.com/shanecav84/fomantic-ui-sass
