### ISSUE TITLE
Javascript assets not loading on heroku

### ISSUE THREAD

**Issue by nicovigil1** [doabit/semantic-ui-sass#137]
I've added eveything to my application.js. I had to hard code the required js for ratings in the html for it to work on localhost, however when I deploy to heroku I cannot get the ratings to show up at all. any clue on how to load the js into the asset pipeline?

**Comment by doabit** [comment]
The latest version?

**Comment by nicovigil1** [comment]
Got it working! Turns out it was loading before the html did - I ended up having to wrap it in a document ready block(?) like so 
```
$(document).ready(function(){
  $('.ui.rating')
    .rating("disable")
    ;
}
)
```
