### ISSUE TITLE
Javascript Insert in Rails 6

### ISSUE THREAD

**Issue by ZephiroRB** [doabit/semantic-ui-sass#140]
How to include javascript in Rails 6?

**Comment by doabit** [comment]
In rails 6, you can still use `app/assets/javascripts/application.js`

```
//= require semantic-ui
```

or use with webpacker https://github.com/rails/webpacker#resolved, but i recommend to use `yarn add semantic-ui`,

**Comment by jlebrijo** [comment]
I am having the same problem:

`yarn add semantic-ui` is not a good idea because it is not automated, this is asking for a Gulp prompt that will break the production deployment in the future.

`//= require semantic-ui` raises the following error:

```
Uncaught ReferenceError: jQuery is not defined
```

Maybe this should be references in `app/javascript/packs/application.js` in order to find JQuery. But how?

Can you help, please?

**Comment by doabit** [comment]
@jlebrijo You can try to  put `<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>` before `javascript_include_tag`.

**Comment by jlebrijo** [comment]
Great point @doabit , thanks!

Finally I could integrate Rails 6 with this gem. Just sharing my complete solution.

We have JQuery as prerequisite: `yarn add jquery popper.js`

After that we have to create $ and jQuery handlers into webpack config, at `packs/application.js`:
```javascript
import JQuery from 'jquery';
window.$ = window.jQuery = JQuery;
```

Finally we have to import all files in the correct order at `views/layouts/application.html.haml`:
```haml
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
```

Then we can do the usual imports. CSS at `assets/stylesheets/application.scss`:
```scss
@import "semantic-ui";
```

And Javascripts at `assets/javascripts/application.js`:
```javascript
//= require semantic-ui
```

**Comment by AlexanderCohen** [comment]
Hey Hey @doabit, I believe the Javascript file has moved in rails 6 from `app/assets/javascripts/application.js` to `app/javascripts/packs/application.js`

I'm not sure that solution still works, or at least it's not working for me. 

Related to this comment:
> In rails 6, you can still use `app/assets/javascripts/application.js`
> 
> ```
> //= require semantic-ui
> ```
> 
> or use with webpacker https://github.com/rails/webpacker#resolved, but i recommend to use `yarn add semantic-ui`,

**Comment by doabit** [comment]
https://github.com/doabit/semantic-ui-sass#ruby-on-rails-version-6-with-webpacker
