### ISSUE TITLE
Asset Import Issue w/ Webpack

### ISSUE THREAD

**Issue by JoshReedSchramm** [doabit/semantic-ui-sass#148]
Hi - Trying to use the package via Rails webpacker and running into webpack compile issues importing the scss file.

I'm getting errors in the compile related to images/fonts in the assets folder. Stuff like 

`Can't resolve '../../assets/fonts/outline-icons.woff2'`

It's entirely possible I'm doing something wrong here but not really sure what. Would love some thoughts if you've seen this. 

Thanks

**Comment by doabit** [comment]
Please use the latest package, see https://github.com/doabit/semantic-ui-sass-rails6-demo

**Comment by JoshReedSchramm** [comment]
Closing this. I didnt even realize i opened it years ago and im back trying to figure out how to make this work w/ shakapacker (unrelated to this issue) - but this issue is stale now.
