### ISSUE TITLE
image gets dimmed automatically in card

### ISSUE THREAD

**Issue by citysheep** [doabit/semantic-ui-sass#35]
When I use "card", I found that dimmer is automatically enabled for any images in it. Can I disable this feature? I want use fade reveal for two images in the cards, and do not want it to be dimmed.

Thank you!

**Comment by doabit** [comment]
Hi, i think you should open a new issue on https://github.com/Semantic-Org/Semantic-UI/issues

**Comment by citysheep** [comment]
Thanks doabit. When I use normal semantic ui I don't see this issue, so I was wondering if this is something related to this sass version of semantic. Will check their repository too.

**Comment by doabit** [comment]
Oh, can you give me a demo?

**Comment by citysheep** [comment]
Sorry for the late reply. I figured out the issue now, it is caused by a bug in my code.
Thank you for your help.
