### ISSUE TITLE
Suggestion: Rename to semantic-ui-rails

### ISSUE THREAD

**Issue by Jakobud** [doabit/semantic-ui-sass#36]
Just a suggestion for you. Keep this project a SASS/SCSS port of Semantic UI instead of a Rails thing. Or at least rename the repo to -rails instead of -sass. Sass started out as a Ruby/Rails thing a long time ago but the number of non-rails users that use it nowadays is extremely high.

**Comment by fahchen** [comment]
+1

**Comment by doabit** [comment]
Sorry, have no plan now.

**Comment by yordis** [comment]
@doabit I really dont care that much but even now I take a look and some guy is trying to cooperate but he doesn't know this is for Rails purpose so :+1: for do this.

**Comment by varemenos** [comment]
+1

**Comment by Jakobud** [comment]
Just another poke on this subject. It doesn't make sense to install this project `bower install semantic-ui-sass` when this project is not a sass project but rather it is a rails project. Rename this to `semantic-ui-rails` or something. Otherwise users end up installing it expecting just a `sass` port of Semantic UI but instead get some rails stuff that they don't understand, need or use.

**Comment by BillyParadise** [comment]
Maybe they should just use Rails then :+1: 

(joke!)

**Comment by rozzzly** [comment]
+1 :+1: when I found this repo I got really excited!! and then really sad.

**Comment by mastito03** [comment]
:+1:
