### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by pixxelboy** [doabit/semantic-ui-sass#41]
Willing to use SUI in a fresh RAILS project, but I'm struggling to understand where or how to overload default theme with my very own custom one.
SUI's semantic.config and theme.config files are perfect. How to apply these to a SASS gem like semantic-ui-sass ?

**Comment by doabit** [comment]
See https://github.com/Semantic-Org/Semantic-UI/issues/1147, sorry, i have no idea now.

**Comment by chrisvel** [comment]
Any idea about that? Should be nice to know how to change themes (default ones) easily.

**Comment by doabit** [comment]
@chrisvel Sorry, i've no idea now, because of sass not support variables inside @import.

**Comment by ctilley83** [comment]
So basically this gem is extremely limited in it's implementation at this time?

**Comment by M-Porter** [comment]
> [...] sass not support variables inside `@import`.

Sass does support variables inside `@import` statements.

With bootstrap sass and rails you can do this:

```scss
$enable-flex: true;
$font-size-root: 14px;
$font-family-sans-serif: 'Roboto', sans-serif;
@import "bootstrap";
```

These would override the variables inside of the imported sass files. So this would actually be fairly easy to implement. The sass files would just have to be changed to real sass files rather than just modularized css files 😄

**Comment by doabit** [comment]
@M-Porter I want to use variables like 

```
$them_name: 'theme_name';
@import $theme_name;
```

But sass doesn't support this now. https://github.com/sass/sass/issues/739

**Comment by radiocity** [comment]
Customize your theme with additional css and optimize with [csso](https://github.com/css/csso)
