### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by adrianratajczak** [doabit/semantic-ui-sass#46]
I've added scss version of semantic but my icons now dissapears.

**Comment by andreslemik** [comment]
need more info, code sample, gem version, etc.

**Comment by davelowndes** [comment]
I have a similar issue. I'm using SilverStripe so have run `compass create -r semantic-ui-sass --using semantic-ui` in my **/[siteroot]/themes/default/** directory. Semantic UI is running but is trying to load fonts and icons from **/[siteroot]/images/semantic-ui/** and **/[siteroot]/images/semantic-ui/**. I tried adding variable `$siteFolder   : 'themes/default/';` to **styles.scss** with no success. I can't find any other references as to how to set up a different path.

**Comment by silaspedrosa** [comment]
Same issue here
