### ISSUE TITLE
Version 2.0 just release

### ISSUE THREAD

**Issue by pareeohnos** [doabit/semantic-ui-sass#48]
It appears that Semantic-UI 2.0 has just been release (today I think?).  This gem should look at bumping the version

**Comment by doabit** [comment]
I'll take a look.

**Comment by sennor** [comment]
👍

**Comment by stunjiturner** [comment]
at least create a branch for version 2, I was just coding in other projects against the new docs and next branch, forgot the gem was still at the 1.xx version, while i am on current project, argh

**Comment by mtcarlso** [comment]
+1

**Comment by BillyParadise** [comment]
It sure would be nice if the Semantic team would at least make the 1.0 docs available on their site.  In the meantime, http://web.archive.org/web/20150618045443/http://semantic-ui.com/ seems to be the last snapshot before 2.0

**Comment by saigemcvea** [comment]
+1
and love the project!

**Comment by doabit** [comment]
Sorry for late update, i've bump a new version.

**Comment by mtcarlso** [comment]
Thanks! Much appreciated.
