### ISSUE TITLE
semantic 2.0

### ISSUE THREAD

**Issue by dekhaus** [doabit/semantic-ui-sass#52]
Hi All

I'm currently using this gem in a Rails backed app that uses AngularJS for its front-end.  

Does this gem support Semantic 2.0 and if so - what steps are necessary to configure an app ?  

I tried updating my bower.json to pull the latest version of Semantic 2.0 and while that seemed to work - when I tried accessing Semantic 2.0 specific functionality (i.e. certain colored buttons that don't exist in Semantic 1.0) - it didn't work.

Thanks
Dave

**Comment by doabit** [comment]
Please read https://github.com/doabit/semantic-ui-sass#semantic-ui-sass-with-rails
