### ISSUE TITLE
Grid is broken

### ISSUE THREAD

**Issue by chrise86** [doabit/semantic-ui-sass#56]
Using

    <div class="ui two column doubling grid container">
      <div class="column">Column 1</div>
      <div class="column">Column 2</div>
    </div>

The columns should obviously sit next to each other, but instead they sit underneath.

Switching to the official release works fine. It looks like it's to do with the load order. A `.ui.container` rule is overwriting a `.ui.grid` rule, forcing `display: block;` instead of the required `display: flex;`.

Propose to either include 'collections' after 'elements', or simply do not categorise them and load in the order of the official build.

**Comment by doabit** [comment]
If only use Semantic UI , have the same issue?

**Comment by chrise86** [comment]
No that's what I mean by switching to the official release. Using the vanilla Semantic UI works fine

**Comment by doabit** [comment]
@chrise86  I have bump a new version. it wokrs well.

**Comment by chrise86** [comment]
Ah ok cool! :+1: I did try replacing the grid file, I guess I must have needed some others too, thanks! I'll test it out before closing, just incase

**Comment by jmayergit** [comment]
I'm using most current version and my grids are not acting properly.

My grid is larger than my body, if I use any standard grid (e.g. ui grid container, ui grid, etc.) Alternatively if I use other types (e.g. ui internally celled grid) the grid is the correct size but then stuff like centered column, row, or grid do not actually center content.

**Comment by doabit** [comment]
@chrise86 Do you have tried to use https://github.com/Semantic-Org/Semantic-UI, not the gem?

**Comment by jmayergit** [comment]
I'm assuming that was meant for me, no and I do not know how I would deploy to Heroku a rails project that required use of npm.

**Comment by doabit** [comment]
Can you show me your grid code?

**Comment by jmayergit** [comment]
http://pastebin.com/d3N4DcmM

Is it possible to use semantic-ui in a rails project when deploying to Heroku?

**Comment by doabit** [comment]
I used the gem and  https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css, got same result.
![ebbc27a7-1033-43ed-8a8b-56d396a18d22](https://cloud.githubusercontent.com/assets/330368/11353112/3a0dd8f4-927b-11e5-8efa-f19ff1a7881d.png)

**Comment by doabit** [comment]
And the semantic-ui  can work on heroku.

**Comment by jmayergit** [comment]
Alright I'm looking into it
