### ISSUE TITLE
No such framework: "semantic-ui"

### ISSUE THREAD

**Issue by ciberch** [doabit/semantic-ui-sass#58]
Hi Guys

I am getting the error 

   `No such framework: "semantic-ui"`

When I run

   `bundle exec compass install semantic-ui`

I am using
Rails 4.2.4

and my Gemfile has

``` ruby
gem "compass-rails"
gem "sass-rails"
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'
```

What am I missing ? I have put

``` ruby
require 'semantic-ui-sass'
```

In `application.rb` (No `config.rb`)

**Comment by doabit** [comment]
If you/re using rails, you should only add  `@import "semantic-ui";` in your scss file.
