### ISSUE TITLE
Publishing to NPM

### ISSUE THREAD

**Issue by pablodenadai** [doabit/semantic-ui-sass#59]
Just wondering if you guys are planning on publishing this package to NPM? Thanks.

**Comment by doabit** [comment]
@ghpabs Sorry, i've no plan to publish to npm, but i'll take a look at it.

**Comment by ghpabs** [comment]
Oh okay. I can only consume npm packages in my project so that's a bummer.

There's not much to it really. Once you have package.json setup you can then just run $ npm publish.

Feel free to close the issue if you decide not to publish it.

**Comment by doabit** [comment]
@ghpabs Because of font url https://github.com/doabit/semantic-ui-sass/blob/master/app/assets/stylesheets/semantic-ui/elements/_icon.scss#L20, i should do something to make it works without rails.

**Comment by harrysolovay** [comment]
This would be extremely useful for me as well. Please publish semantic-ui-sass as an NPM package. It would make my day :)

**Comment by ikhilko** [comment]
i'm just published fork into npm https://www.npmjs.com/package/semantic-ui-sass, also i can create pull request into this rep, or if you want i will sync fork with your updates and publish it into npm.

**Comment by doabit** [comment]
@ikhilko Thanks for your work, you could pull request or i add your npm in README.
