### ISSUE TITLE
ID option for `semantic_icon` helper

### ISSUE THREAD

**Issue by kntmrkm** [doabit/semantic-ui-sass#60]
I want to add ID attr to `semantic_icon` helper.

like below...

```
= semantic_icon :some, { id: 'some-id' }
# => <i class='some icon' id='some-id'>
```

How do u think?

thanks.

**Comment by doabit** [comment]
@kntmrkm I've updated to add id attr to semantic_icon helper, you can try with the master branch.

**Comment by kntmrkm** [comment]
Thanks for your quick response!

It works! great!
