### ISSUE TITLE
Dropdown broken

### ISSUE THREAD

**Issue by JoelKlint** [doabit/semantic-ui-sass#65]
Hi, 

The dropdown seems to be broken. I am using it a menu.
The dropdown box displays but it wont dropdown on click, showing it's children.
'simple dropdown' works fine.

Do you know if it is broken?

**Comment by chrisvel** [comment]
did it was a problem or not ?

**Comment by doabit** [comment]
@chrisvel You should add 

```javascript
$(function(){
  $('.ui.dropdown').dropdown();
})
```

http://semantic-ui.com/modules/dropdown.html#/usage

**Comment by chrisvel** [comment]
@doabit thank you
