### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by dajwilli** [doabit/semantic-ui-sass#66]
I am running into a really weird issue with form validations. The validation display perfectly in development but don't display at all in production. The really odd thing is that there are no console errors which makes you think it should be working.

Do you have any idea of what could be causing the problem? Or has anyone else ran into similar problems?

**Comment by doabit** [comment]
Could you test it with `Semantic UI`?

**Comment by dajwill** [comment]
Sorry, it was just a problem with my asset pipeline on heroku. Thanks for getting back though.
