### ISSUE TITLE
Problem with icons in version 2.2.0.0

### ISSUE THREAD

**Issue by maurosbu** [doabit/semantic-ui-sass#78]
Icons are not rendered (squares) because fonts are not found.

Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.example.com/themes/default/assets/fonts/icons.woff2

Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.example.com/themes/default/assets/fonts/icons.woff 

Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.example.com/themes/default/assets/fonts/icons.ttf

**Comment by chrisvel** [comment]
+1 from me, I just realised that and went back to 2.1.8.0.

**Comment by doabit** [comment]
Sorry for the mistake, please update to 2.2.1.0.

**Comment by chrisvel** [comment]
Does the same thing occur with 2.2.2 ?

**Comment by maurosbu** [comment]
It is working with 2.2.2
