### ISSUE TITLE
google fonts is blocked in China

### ISSUE THREAD

**Issue by Lovelcp** [doabit/semantic-ui-sass#80]
Because semantic-ui default loading google fonts：https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin,latin-ext, so the fonts location is blocked by Chinese Greate Wall. I have currently saw some pull request, like #64  and #70 . I really hope these PRs could be merged. Or is there another way to change the default fonts url? If using raw semantic-ui, this problem can be solved in this way: https://github.com/Semantic-Org/Semantic-UI/issues/1305

**Comment by doabit** [comment]
@Lovelcp Please use master branch, https://github.com/doabit/semantic-ui-sass#custom-font

**Comment by Lovelcp** [comment]
Thank you very much!!!!!!!!!!!!!!!!!!!!!
