### ISSUE TITLE
Update to 2.2.2

### ISSUE THREAD

**Issue by Siprah** [doabit/semantic-ui-sass#84]
I have a problem with updating Semantic UI to latest version. 

I typed `bundle install`,  console says that new version has been installed. But when I'm looking on JavaScript file, I'm still seeing `Semantic UI - 2.1.7` in comment. I tried use `asset:clean` command but it don't working. Why?

**Comment by doabit** [comment]
@Siprah Hi, could you try `rake assets:clobber && rake assets:precompile`?

**Comment by doabit** [comment]
I closed this issue, if you've any question, you can reopen it.
