### ISSUE TITLE
Disable Google Fonts.

### ISSUE THREAD

**Issue by mrkongo** [doabit/semantic-ui-sass#85]
Can we use:

```
@importGoogleFonts: false;
```

in our application.scss to disable Google Fonts?

**Comment by doabit** [comment]
You can use https://github.com/doabit/semantic-ui-sass#custom-font

**Comment by mrkongo** [comment]
Nope. Dear @doabit, I just want to disable at all Google fonts. I need just Helvetica and Windows font, like Bootstrap. The fonts loaded after Lato in Semantic.

**Comment by doabit** [comment]
@mrkongo If you want to use custom font, look at https://github.com/doabit/semantic-ui-sass/commit/0d9aab026a3603c812248669b9aa6da466bd36ca, it should work for you.

**Comment by mrkongo** [comment]
No, dear @doabit , I need to disable Google fonts. How to?

**Comment by doabit** [comment]
@mrkongo Use `$font-url: font_url`, font_url can use googe font or your custom font, `$font-name: "font_name"`

**Comment by mrkongo** [comment]
Perhaps I did not make myself clear. I need to remove Google Fonts at all. How to? I need to remove google fonts loading and the first "Lato" font from font-family. Is it clear now? In semantic-ui less I can use `@importGoogleFont: false` to not use the google fonts (Lato still remains in font-family anyway... at least for now...)

**Comment by doabit** [comment]
@mrkongo Sorry, there is no way now, i always use `$font-url` and `$font-name` to use custom font and disable google font.

**Comment by mrkongo** [comment]
And if I use

```
$font-url: '';
$font-name: '';
```

in my css I have `font-family: "", "Helvetica"...``` right?

**Comment by mrkongo** [comment]
Yes, nothing before `"Helvetica"...`.

**Comment by doabit** [comment]
@mrkongo Hi, please use master branch and use `$font-family: ....`
