### ISSUE TITLE
Slow refresh on any css change with @import "semantic-ui";

### ISSUE THREAD

**Issue by MainShayne233** [doabit/semantic-ui-sass#86]
With:

``` scss
@import "semantic-ui";
```

in my application.scss, I was getting incredibly slow refresh times anytime any CSS (not just semantic stuff) was touched.

After replacing with;

``` scss
 *= require semantic-ui
```

the problem disappears.

**Comment by doabit** [comment]
@MainShayne233 Because `@import "semantic-ui"` will load many sass files, you can use `guard` and 'livereload' to speed up it.

**Comment by ishouvik** [comment]
Same issue here. I use guard and livereload and still it's very slow.

**Comment by SocoolWON** [comment]
Same issue here too.

**Comment by pedantic-git** [comment]
If you change 'sass-rails' to 'sassc-rails' in your Gemfile, you'll notice a huge performance improvement (sassc is the native version of Sass, which is much faster than the pure-Ruby version).

**Comment by ishouvik** [comment]
@pedantic-git Thank you very much for the suggestion. I will definitely try it out.

**Comment by parhs** [comment]
sassc isnt always the solution. Does *= require semantic-ui have any side effects?
