### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$font-name".

### ISSUE THREAD

**Issue by edipofederle** [doabit/semantic-ui-sass#89]
Hello,

I use @import instead of include all semantic-ui. But when I execute: RAILS_ENV=production bundle exec rake assets:precompile I got a

Sass::SyntaxError: Undefined variable: "$font-name". ([full log](https://gist.github.com/edipofederle/cc3c230fa723d519ab4f8765ced13c4c))

```
@import 'semantic-ui/globals/all';
@import 'semantic-ui/elements/button';
@import 'semantic-ui/elements/header';
@import 'semantic-ui/elements/icon';
@import 'semantic-ui/elements/input';
@import 'semantic-ui/elements/label';
@import 'semantic-ui/elements/segment';
@import 'semantic-ui/elements/divider';
@import 'semantic-ui/collections/form';
@import 'semantic-ui/collections/grid';
@import 'semantic-ui/collections/menu';
@import 'semantic-ui/collections/message';
@import 'semantic-ui/collections/table';
@import 'semantic-ui/modules/checkbox';
@import 'semantic-ui/modules/dropdown';
@import 'semantic-ui/modules/dimmer';
@import 'semantic-ui/modules/modal';
@import 'semantic-ui/modules/sidebar';
@import 'semantic-ui/modules/transition';
@import 'semantic-ui/modules/popup';
@import 'semantic-ui/modules/tab';
```

Any tip here?

Thanks in advance

**Comment by doabit** [comment]
@edipofederle I've tested and it works. which version did you use?
![5fadaae4-b4b2-4a80-90c6-ae8328ca46a0](https://cloud.githubusercontent.com/assets/330368/17876628/7bf86864-690e-11e6-8910-1018642bfc8f.png)
![0e935c63-59ca-4672-9097-0d2cfb1d3a1b](https://cloud.githubusercontent.com/assets/330368/17876630/7d8a6880-690e-11e6-8046-8cd6b2d91e37.png)

**Comment by edipofederle** [comment]
Hi @doabit 

I just add this to Gemfile:

gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'

**Comment by doabit** [comment]
@edipofederle I think you don't need to add `config.assets.precompile = ['*.js', '*.css', '*.css.erb', '*.png', '*.gif', '*.svg', '*.eot', '*.woff', '*.ttf']` to `production.rb`.

**Comment by edipofederle** [comment]
@doabit 

Sorry for late reply.

My mistake here. Sorry :( and thanks.

Best,
