### ISSUE TITLE
$import-google-fonts: false is not work

### ISSUE THREAD

**Issue by destinyd** [doabit/semantic-ui-sass#91]
I create a scss file **app/assets/stylesheets/semantic-ui-overrider.scss

```
$import-google-fonts: false;
@import 'semantic-ui';
```

and require it in application.scss

```
//= require 'semantic-ui-overrider'
```

It still load **https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin,latin-ext**

**Comment by destinyd** [comment]
gem version: 2.2.4.0

**Comment by doabit** [comment]
@destinyd You should use `gem "semantic-ui-sass", github: 'doabit/semantic-ui-sass'`
