### ISSUE TITLE
Sass Undefined variable $font-family 

### ISSUE THREAD

**Issue by choilive** [doabit/semantic-ui-sass#92]
I seem to be having an issue upgrading my gem semantic-ui-sass from 2.2.0 to 2.2.6. I am on Rails 5.
I am getting an undefined variable for $font-family. Probably related to the "Add font-family variable" commit. It is triggering on the _form file specifically.

`Sass::SyntaxError - Undefined variable: "$font-family".:
   () Users/michaelchoi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/semantic-ui-sass-0405e7002c7d/app/assets/stylesheets/semantic-ui/collections/_form.scss:102:in '
   () Users/michaelchoi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/semantic-ui-sass-0405e7002c7d/app/assets/stylesheets/semantic-ui/collections/_all.scss:2:in '`

Any ideas on how to get around it? I have tried adding a $font-family to my application.scss.css file but no luck there.

**Comment by doabit** [comment]
@choilive I've tested, it works.

`base.scss`

```css
@import 'semantic-ui';
```

`application.css`

```css
/*
 *= require posts
 */
```

**Comment by RuBAN-GT** [comment]
I have this problem too, when tris to do assets precomplie.

**Comment by doabit** [comment]
@RuBAN-GT I used the master branch and it works.

base.scss

```sass
@import 'semantic-ui';
```

application.css

```sass
/*
 *= require base
 */

```
<img width="1440" alt="2016-11-14 8 46 15" src="https://cloud.githubusercontent.com/assets/330368/20250231/e869cbc2-aa46-11e6-8545-2ed51a373f43.png">

**Comment by RuBAN-GT** [comment]
@doabit, Yes, thank you: it was my error of rails configuration.

**Comment by dadave92** [comment]
@RuBAN-GT, How did you solve this error?

**Comment by kovirolik** [comment]
@dadave92 don't use modules. Import all SemanticUI

**Comment by EnglishLanguageInstitute** [comment]
I am having this same issue.  I am trying to move my application to a new production server.  I am using the exact same codebase as is running perfectly fine on the original production server.  Everything looks like it deploys fine, but the assets don't all display correctly.  So I try to run the precompile at the command line and I get the same error: "Sass::SyntaxError - Undefined variable: "$font-family"."  I have tried doing exactly as stated above to solve it and it continues to give me the error.  Any other ideas?

**Comment by doabit** [comment]
@EnglishLanguageInstitute Which version?

**Comment by EnglishLanguageInstitute** [comment]
@doabit  The current version I have working on my production server and the first one I tried on the new server is 2.2.12.0.  I have tried 2.2.14 on the new server as well with the same result.

**Comment by doabit** [comment]
@EnglishLanguageInstitute Sorry, i have tested and it works on my mac book and ubuntu server, i use rails 5.2 and `gem 'semantic-ui-sass', '>= 2.2.14'`,  'https://github.com/doabit/semantic-ui-sass/issues/92#issuecomment-260226109'

**Comment by edipofederle** [comment]
I still facing this issue right now, some more tips into this ?

Thanks
