### ISSUE TITLE
Sass::SyntaxError during precompile for Heroku deploy

### ISSUE THREAD

**Issue by alfredoliverwillder** [doabit/semantic-ui-sass#95]
`rake assets:precompile` fails with:

`Sass::SyntaxError: Invalid CSS after "...color: radial, ": expected expression (e.g. 1px, bold), was ", transparent 4..."`

This originates from /modules/_embed.scss where `background` is being set with `radial-gradient`. Unfortunately I do not know how to fix :/ 

Have @imported 'around' this for now in order to deploy successfully.

**Comment by doabit** [comment]
Which version? I used the master version and it works.

**Comment by jfredson** [comment]
I'm currently having this prbolem while attempting to deploy. Did you find a fix?
