### ISSUE TITLE
error: "Undefined variable" when import specific modules

### ISSUE THREAD

**Issue by BoleLee** [doabit/semantic-ui-sass#96]
I tried to import only form module:
`@import "semantic-ui/collections/form";`
but it appeared error: Undefined variable: $font-family;
Then I modified it to:
`@import "semantic-ui/globals/site";
@import "semantic-ui/collections/form";`
it appeared error: Undefined variable: $import-google-fonts

I have no idea what goes wrong, am I doing something wrong?

**Comment by doabit** [comment]
@BoleLee Please try 

```scss
@import "semantic-ui/globals/all";
@import "semantic-ui/collections/form";
```
or

```scss
@import "semantic-ui/globals/variables";
@import "semantic-ui/collections/form";
```

**Comment by BoleLee** [comment]
Both ways work, Thank you~~ @doabit
