### ISSUE TITLE
Font not changing.

### ISSUE THREAD

**Issue by rehan-dev** [doabit/semantic-ui-sass#98]
After adding $font-url: 'something'; before @import "semantic-ui"; but unfortunately font not change any suggestion ?

**Comment by doabit** [comment]
@rehan-dev Which version?

**Comment by rehan-dev** [comment]
its semantic-ui-sass(v2.2.7.1, ruby-2.2.6-p396)[gem]

**Comment by rehan-dev** [comment]
@doabit any update ?

**Comment by doabit** [comment]
@rehan-dev Sorry for late reply, i have tested with v2.2.7.1, it could work. 

```scss
 $font-url: 'http://fonts.useso.com/css?family=Lato:400,700,400italic,700italic&subset=latin';
 @import "semantic-ui";
```

If you want to use custom font family, please use 

```scss
$font-name: 'something';
```

or

```scss
$font-family: 'something', 'Helvetica Neue', Arial, Helvetica, sans-serif;
```

**Comment by Halt** [comment]
i have the same issue
